# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67551672614c0b9b1afbf3f7285b99326155f224ea6c5c08508d0d60768faf4fc041162fe773c6049d26349d2433b4ad6692fd8ec01e69487ef6fa30991aa7a3

test:
  secret_key_base: 70d81884f0b2874131871909805759a51666e41e69537018a475337027882066430a7667d3ef915acadd31835cc347b944a1816b33cd2ad27ec0b4ad2f637143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
